MODEL:
  NAME: "ResCLANet"
  RESNET:
    DILATIONS: (1, 2)
    STRIDES: (-1, -1)
  CLANET:
    CONTEXT: "gap"
    FUSE_3X3: True
DATASET:
  NAME: "cityscapes"
  PATH: "data/cityscapes/"
  TRAIN: ("train", "val")
  TEST: "test"
  NUM_CLASSES: 19
  TRANSFORMS:
    CROP_SIZE: (1024, 1024)
    BLUR: "gblur"
LOSS:
  AUX_WEIGHT: 1.0
SOLVER:
  ITERATION_BASED: True
  BATCH_SIZE: 16
  BASE_LR: 0.01
  MAX_ITERS: 80000
  CHECKPOINT_PERIOD: 2000
  TEST_PERIOD: 2000
TEST:
  BATCH_SIZE: 8
OUTPUT_DIR: "output/clanet_wgap_fuse3x3_dilated_r18_cityscapes_trainval_100k_iters"
