MODEL:
  NAME: "ResCLANet"
  RESNET:
    DILATIONS: (1, 2)
    STRIDES: (-1, -1)
  CLANET:
    CONTEXT: "gap"
    FUSE_3X3: True
DATASET:
  NAME: "ade20k"
  PATH: "/cluster_home/custom_data/ade/ADEChallengeData2016/"
  # PATH: "data/ade/ADEChallengeData2016/"
  TRAIN: ("training",)
  TEST: "validation"
  NUM_CLASSES: 150
  TRANSFORMS:
    CROP_SIZE: (512, 512)
    BLUR: "gblur"
LOSS:
  AUX_WEIGHT: 1.0
SOLVER:
  ITERATION_BASED: True
  BATCH_SIZE: 32
  BASE_LR: 0.01
  MAX_ITERS: 160000
  CHECKPOINT_PERIOD: 2000
  TEST_PERIOD: 2000
TEST:
  INPUT_MODE: "resize"
  SIZE: (512, 2048)
  BATCH_SIZE: 8
OUTPUT_DIR: "output/clanet_r18_ade20k_160k_32batch"
