MODEL:
  NAME: "DFCLANet"
  PRETRAINED: "pretrained_models/df2_imagenet.pth"
  CLANET:
    HEAD: "CLALightHead"
DATASET:
  NAME: "cityscapes"
  PATH: "/cluster_home/custom_data/cityscapes/"
  TRAIN: ("train", "val")
  TEST: "val"
  NUM_CLASSES: 19
  TRANSFORMS:
    CROP_SIZE: (1024, 1024)
    BLUR: "gblur"
LOSS:
  AUX_WEIGHT: 1.0
SOLVER:
  ITERATION_BASED: True
  BATCH_SIZE: 16
  BASE_LR: 0.01
  MAX_ITERS: 80000
  CHECKPOINT_PERIOD: 2000
  TEST_PERIOD: 4000
TEST:
  BATCH_SIZE: 8
OUTPUT_DIR: "output/clanet_df2_cityscapes_pretrain_80k_iters"
